version: '2.2'

services:
  create_certs:
    image: elasticsearch
    container_name: create_certs
    build:
      context: ./provisioning/elasticsearch
      dockerfile: Dockerfile
    command: >
      bash -c '
        yum install -y -q -e 0 unzip;
        if [[ ! -f /certs/bundle.zip ]]; then
          bin/elasticsearch-certutil cert --silent --pem --in config/certificates/instances.yml -out /certs/bundle.zip;
          unzip /certs/bundle.zip -d /certs;
        fi;
        chown -R 1000:0 /certs
      '
    working_dir: /usr/share/elasticsearch
    volumes:
      - certs:/certs
      - .:/usr/share/elasticsearch/config/certificates
    networks:
      - cdc

volumes:
  certs:
    driver: local

networks:
  cdc:
    driver: bridge