version: '3.4'
services:
  mariadb-cdc:
    image: mariadb-cdc
    container_name: mariadb-cdc
    build:
      context: ./provisioning/mysql
      dockerfile: Dockerfile
    ports:
      - "4406:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=000000
    networks:
      - cdc

  syncer:
    image: ${DOCKER_REGISTRY-}syncer
    build:
      context: ./sync/Syncer
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    networks:
      - cdc
    depends_on:
      - mariadb-cdc

networks:
cdc:
    external: true